### ISSUE TITLE
Python syntax highlighting 

### ISSUE THREAD

**Issue by Timfrazer** [PyBites-Open-Source/pybites-tips#2]
I would like to add python syntax highlighting using.[ rich text for beautiful formatting in the terminal.]( https://github.com/willmcgugan/rich) - This would make it easier to read from the console.

<img width="1107" alt="example" src="https://user-images.githubusercontent.com/874784/95666597-33780380-0b29-11eb-863c-3795eba27d5a.png">

**Comment by bbelderbos** [comment]
@Timfrazer cool idea, looking forward to the PR

**Comment by jarviscodes** [comment]
I worked on this issue as I had never used `rich` and syntax highlighting before.
PR #3 ready!

**Comment by bbelderbos** [comment]
Sweet thanks @jarviscodes, I will review later ...

**Comment by jarviscodes** [comment]
@bbelderbos I think this can be closed now since #3 got merged!

**Comment by bbelderbos** [comment]
Yep thanks for coding that up!
